namespace SchemaCompare.Services;

/// <summary>One keyword's teaching content for the ✨ explainer dialog.</summary>
public sealed record SqlKeywordInfo(
    string Keyword,
    string Title,
    string Category,
    string Explanation,
    string Example,
    string Tips);

/// <summary>
/// Static, hand-written explanations for the ✨ Explain dropdown — aggregation
/// functions first, then the clauses they pair with. No AI, no I/O.
/// </summary>
public static class SqlKeywordLibrary
{
    public static readonly List<SqlKeywordInfo> All =
    [
        new("SUM",
            "Adds values together",
            "Aggregate",
            "SUM walks every row in the group and adds the column's values into one total. NULL values are skipped entirely — a group with only NULLs returns NULL, not zero.",
            "SELECT Category, SUM(Price) AS TotalPrice\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "Only works on numbers. Ignores NULLs. Use with GROUP BY to get one total per group; without GROUP BY the whole table is one group."),
        new("AVG",
            "Average of the values",
            "Aggregate",
            "AVG adds up the values in the group and divides by how many non-NULL values there were. Averages of averages are wrong — average the raw rows, not pre-averaged numbers.",
            "SELECT Category, AVG(Price) AS AvgPrice\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "Ignores NULLs. Beware of integer division — AVG on an int column truncates; cast to float first: AVG(CAST(Qty AS FLOAT))."),
        new("COUNT",
            "Counts values",
            "Aggregate",
            "COUNT(column) counts how many rows have a non-NULL value in that column. COUNT(*) counts every row including NULLs — usually what you want for 'how many rows'.",
            "SELECT Category, COUNT(*) AS RowsInGroup,\r\n       COUNT(Discount) AS RowsWithDiscount\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "COUNT(*) = all rows. COUNT(col) = rows where col is not NULL. Both return an int; use COUNT_BIG when counts might exceed 2 billion."),
        new("COUNT(*)",
            "Counts every row",
            "Aggregate",
            "COUNT(*) is the fastest way to ask 'how many rows?' — it counts rows regardless of any column values, including rows that are entirely NULL.",
            "SELECT COUNT(*) AS TotalProducts\r\nFROM dbo.Products\r\nWHERE Price > 100;",
            "Pairs with GROUP BY for per-group counts, and with HAVING COUNT(*) > N to keep only busy groups."),
        new("COUNT_BIG",
            "COUNT that can count higher",
            "Aggregate",
            "COUNT_BIG works exactly like COUNT but returns a bigint, so it can count past the 2,147,483,647 limit of a normal int.",
            "SELECT COUNT_BIG(*) AS TotalRows\r\nFROM dbo.BigTransactionLog;",
            "Use for huge tables or totals you might add up. Also common in index maintenance checks (sys.dm_db_index_physical_stats comparisons)."),
        new("MIN",
            "Smallest value",
            "Aggregate",
            "MIN returns the smallest value in the group. Works on numbers, dates, and text (alphabetical order). NULLs are ignored.",
            "SELECT Category, MIN(Price) AS Cheapest\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "On a datetime column it finds the earliest record — great for 'first order ever'. Can use an index seek, so it is often instant."),
        new("MAX",
            "Largest value",
            "Aggregate",
            "MAX returns the largest value in the group. Works on numbers, dates, and text. NULLs are ignored.",
            "SELECT Category, MAX(Price) AS MostExpensive\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "On a datetime column it finds the latest activity — great for 'last login'. Like MIN it can often read just the index edges."),
        new("STDEV",
            "How spread out the values are",
            "Aggregate",
            "STDEV (statistical standard deviation) measures how far values typically sit from the average. Small = values cluster tightly; large = values are all over the place. It is the sample version (divides by n-1).",
            "SELECT Category, STDEV(Price) AS PriceSpread\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "Needs at least 2 non-NULL values or it returns NULL. Use STDEVP when your rows are the whole population, not a sample."),
        new("STDEVP",
            "Spread of the whole population",
            "Aggregate",
            "STDEVP is the population standard deviation — like STDEV but it divides by n instead of n-1. Use it when the rows you have are every row that exists, not a sample.",
            "SELECT STDEVP(Price) AS PopulationSpread\r\nFROM dbo.Products;",
            "Result is slightly smaller than STDEV on the same data. If in doubt for business data, STDEV (sample) is the usual choice."),
        new("VAR",
            "Variance (squared spread)",
            "Aggregate",
            "VAR is the sample variance — STDEV squared. It weighs outliers much more heavily because big gaps get squared. Useful as a building block for statistics.",
            "SELECT VAR(Price) AS PriceVariance\r\nFROM dbo.Products;",
            "Units are squared (dollars², kg²) which makes it hard to read — take the square root (STDEV) when presenting to humans."),
        new("VARP",
            "Population variance",
            "Aggregate",
            "VARP is the population variance — the whole-population sibling of VAR. Divides by n instead of n-1.",
            "SELECT VARP(Price) AS PopulationVariance\r\nFROM dbo.Products;",
            "Same usage rule as VAR but for complete datasets. STDEVP = SQRT(VARP)."),
        new("STRING_AGG",
            "Glues text values into one string",
            "Aggregate",
            "STRING_AGG joins every row's text value into a single string with a separator of your choice. Perfect for comma-separated lists per group.",
            "SELECT Category,\r\n       STRING_AGG(Name, ', ') AS NamesInCategory\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "SQL Server 2017+. Add WITHIN GROUP (ORDER BY Name) to control the order. Long results can overflow the 8000-byte limit — CAST an input to NVARCHAR(MAX) to lift it."),
        new("GROUP BY",
            "Squash rows into groups",
            "Clause",
            "GROUP BY collapses rows that share the same value into one result row per group. Any column you select must either be in the GROUP BY or wrapped in an aggregate like SUM/COUNT.",
            "SELECT Category, COUNT(*) AS N\r\nFROM dbo.Products\r\nGROUP BY Category;",
            "Think of it as 'one row per X'. Multiple columns group by each unique combination. Filter the groups with HAVING, not WHERE."),
        new("HAVING",
            "Filter AFTER grouping",
            "Clause",
            "HAVING is WHERE for groups. WHERE removes rows before grouping; HAVING removes groups after the aggregates are computed. That's why HAVING can use SUM/COUNT and WHERE cannot.",
            "SELECT Category, COUNT(*) AS N\r\nFROM dbo.Products\r\nGROUP BY Category\r\nHAVING COUNT(*) > 5;",
            "Order of execution: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. Use WHERE when you can — it shrinks the work before grouping."),
        new("WHERE",
            "Filter rows BEFORE grouping",
            "Clause",
            "WHERE keeps only the rows that pass the condition. It runs before grouping and aggregation, so it cannot see aggregates — only row values.",
            "SELECT * FROM dbo.Products\r\nWHERE Price > 30003 AND Status = 1;",
            "Sargable conditions (column on the left, no functions) can use indexes. Use HAVING to filter groups instead."),
        new("DISTINCT",
            "Remove duplicate rows",
            "Clause",
            "DISTINCT collapses identical rows in the result into a single row each. 'Show me the unique combinations of these columns.'",
            "SELECT DISTINCT Category, Country\r\nFROM dbo.Suppliers;",
            "DISTINCT applies to the whole selected row, not one column. It can hide a JOIN bug that duplicates rows — investigate before relying on it."),
        new("TOP",
            "Limit the result size",
            "Clause",
            "TOP n returns only the first n rows of the result. Without ORDER BY 'first' is undefined — always pair TOP with ORDER BY for meaningful results.",
            "SELECT TOP 10 Name, Price\r\nFROM dbo.Products\r\nORDER BY Price DESC;",
            "TOP 10 WITH TIES includes rows equal to the last one. TOP works with PERCENT too. For paging, OFFSET/FETCH is the modern choice."),
        new("ORDER BY",
            "Sort the result",
            "Clause",
            "ORDER BY sorts the final result set — ascending (ASC) by default, DESC for descending. It runs almost last, after WHERE/GROUP BY/HAVING and the SELECT list.",
            "SELECT Name, Price FROM dbo.Products\r\nORDER BY Price DESC, Name ASC;",
            "Can reference column aliases from SELECT. Sorting is expensive on huge sets — combine with TOP when you only need the head of the list."),
        new("INNER JOIN",
            "Only rows that match both sides",
            "Join",
            "INNER JOIN pairs each left row with every matching right row; rows without a match on either side disappear.",
            "SELECT o.Id, c.Name\r\nFROM dbo.Orders o\r\nINNER JOIN dbo.Customers c ON c.Id = o.CustomerId;",
            "Watch for duplicate matches multiplying rows. Filter on the left table with WHERE, on the right table in either ON or WHERE (same result for INNER)."),
        new("LEFT JOIN",
            "Keep all left rows, matches optional",
            "Join",
            "LEFT JOIN keeps every row from the left table; right-side columns become NULL when there is no match. The standard way to ask 'including the ones without…'.",
            "SELECT c.Name, COUNT(o.Id) AS Orders\r\nFROM dbo.Customers c\r\nLEFT JOIN dbo.Orders o ON o.CustomerId = c.Id\r\nGROUP BY c.Name;",
            "Testing the right side must happen in WHERE with IS NULL (or in ON) — putting it in WHERE as = value silently turns it into an INNER JOIN."),
        new("OFFSET / FETCH",
            "Paging — skip and take",
            "Clause",
            "OFFSET n ROWS skips n rows; FETCH NEXT m ROWS ONLY then takes m. The standard way to render page k of a sorted list. Requires an ORDER BY.",
            "SELECT Name FROM dbo.Products\r\nORDER BY Id\r\nOFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY;",
            "Great for paging UIs. For deep pages (OFFSET 100000) performance drops — keyset paging ('WHERE Id > @last') stays fast."),
    ];

    public static SqlKeywordInfo? Find(string keyword) =>
        All.FirstOrDefault(k => string.Equals(k.Keyword, keyword, StringComparison.OrdinalIgnoreCase));
}
