"""One-line purpose per source file, consumed by docs/build_docs.py.

Key = path relative to the repository root. Keep lines short and factual: they are
repeated verbatim in docs/INDEX.md, where an agent decides which file to open.
Anything missing here falls back to the file's own first doc comment and gets
flagged in the index, so add a line when you add a file.
"""

PURPOSES = {
    # ── (root) ──
    "App.axaml": "Application markup: merges the app styles, and the Fluent/DataGrid/AvaloniaEdit themes.",
    "App.axaml.cs": "Avalonia Application: applies saved display settings on startup and opens the startup window.",
    "Program.cs": "STAThread entry point: crash logging for unhandled exceptions, then the Avalonia app builder.",

    # ── Views: windows ──
    "Views/MainWindow.axaml": "Layout of the launcher window: source/target scripts, compare, the one script pane that toggles UP/DOWN, buttons into every other window.",
    "Views/MainWindow.axaml.cs": "Launcher window code-behind: opens saved connections, copies and saves whichever script the pane shows, and every other window from the menu.",
    "Views/QueryWindow.axaml": "Layout of the query window: tab strip, SQL editor, results grid, messages, plan panes.",
    "Views/QueryWindow.axaml.cs": "Query window code-behind: shortcuts (F5/Ctrl+L/Ctrl+F/Ctrl+M/Ctrl+B/Ctrl+G), open/save .sql, drag-drop, clipboard guard, session restore on close.",
    "Views/DbManagerWindow.axaml": "Layout of Object Explorer: server/database tree, filter bar, and the Data/Structure/Definition/Execute tabs.",
    "Views/DbManagerWindow.axaml.cs": "Object Explorer code-behind: tree context menus, Script-As, dialog hosts (restore, backup, properties, script confirm), filter UI wiring.",
    "Views/DbHealthWindow.axaml": "Layout of the DB Health window: CPU/waits/processes/missing-indexes/query-store/error-log tabs, Activity Monitor style.",
    "Views/DbHealthWindow.axaml.cs": "DB Health code-behind: refresh timer, the clipboard and script-confirmation hosts every write verb (KILL, Query Store force/unforce/enable) needs, and the window-scoped shutdown.",
    "Views/DiagramWindow.axaml": "Layout of the database diagram window: toolbar, search, canvas.",
    "Views/DiagramWindow.axaml.cs": "Diagram window code-behind: zoom (incl. Ctrl+wheel), pan, drag, save/load of the layout.",
    "Views/QueryBuilderWindow.axaml": "Layout of the visual Query Constructor dialog.",
    "Views/QueryBuilderWindow.axaml.cs": "Constructor dialog code-behind: modal host for QueryBuilderViewModel, applies generated SQL back to the calling tab.",
    "Views/QueryHistoryWindow.axaml": "Layout of the query history window: search box and entry list.",
    "Views/QueryHistoryWindow.axaml.cs": "History window code-behind: filters persisted history and copies or reopens a chosen script.",
    "Views/BackupWindow.axaml": "Layout of the BACPAC export window (DacFx), separate from the native .bak backup dialog.",
    "Views/BackupWindow.axaml.cs": "BACPAC export code-behind: picks a database, runs DatabaseBackupService, reports progress.",
    "Views/MoveDataWindow.axaml": "Layout of the data-move wizard: source/target picker, table list, plan preview.",
    "Views/MoveDataWindow.axaml.cs": "Data-move code-behind: builds the DataMovePlan, confirms, and runs DataMoveService with progress.",
    "Views/AboutWindow.axaml": "Layout of the About/diagnostics dialog.",
    "Views/AboutWindow.axaml.cs": "About code-behind: version and environment facts, log tail, copy-to-diagnostics text.",

    # ── Views: dialogs ──
    "Views/RestoreDatabaseDialog.axaml": "Layout of the safe restore dialog: media path, backup set picker, relocation grid, options, script preview.",
    "Views/RestoreDatabaseDialog.axaml.cs": "Restore dialog logic (RestoreDraft, RestoreFileRow): STOPAT validation, relocation re-suggestions, REPLACE gating, warnings that block OK.",
    "Views/BackupDatabaseDialog.axaml": "Layout of the native BACKUP DATABASE/LOG dialog.",
    "Views/BackupDatabaseDialog.axaml.cs": "Backup dialog logic (BackupDraft): server-side default path, backup type, APPEND vs FORMAT, VERIFY ONLY, preview and OK gating.",
    "Views/TablePropertiesDialog.axaml": "Layout of the read-only table properties view.",
    "Views/TablePropertiesDialog.axaml.cs": "Table properties dialog: renders a TableProperties snapshot (space, columns, keys, indexes, triggers, stats, partitions).",
    "Views/DbPropertiesDialog.axaml": "Layout of the read-only database properties view.",
    "Views/DbPropertiesDialog.axaml.cs": "Database properties dialog: renders the options/summary DbManagerService reads for one database.",
    "Views/NewIndexDialog.axaml": "Layout of the New Index dialog.",
    "Views/NewIndexDialog.axaml.cs": "New Index dialog: collects an IndexSpec and hands the generated CREATE INDEX script to the caller.",
    "Views/CreatePartitionDialog.axaml": "Layout of the Create Partition dialog.",
    "Views/CreatePartitionDialog.axaml.cs": "Create Partition dialog: collects a PartitionSpec and returns the partition function/scheme plus split script.",
    "Views/ScriptActionDialog.axaml": "Layout of the run-or-copy script confirmation dialog.",
    "Views/ScriptActionDialog.axaml.cs": "Script confirmation dialog: shows the exact T-SQL about to run, returns true only when the user approves execution.",
    "Views/QueryExplainDialog.axaml": "Layout of the plain-English explain-query dialog.",
    "Views/QueryExplainDialog.axaml.cs": "Explain dialog: headline, step-by-step breakdown and deterministic safety warnings for the selected SQL.",
    "Views/AggregationExplainerDialog.axaml": "Layout of the keyword explainer dialog.",
    "Views/AggregationExplainerDialog.axaml.cs": "Keyword explainer: hand-written meaning, example T-SQL and tips for one SQL keyword.",
    "Views/DataCompareWindow.axaml": "Layout of the data compare window: two connections, table list, differing rows, sync script.",
    "Views/DataCompareWindow.axaml.cs": "Data compare code-behind: supplies the save-file and clipboard hooks the view-model needs once its DataContext arrives.",
    "Views/DependenciesDialog.axaml": "Layout of the read-only object dependencies dialog: uses and used-by grids with an empty state.",
    "Views/DependenciesDialog.axaml.cs": "Dependencies dialog: static ShowAsync host for one ObjectDependencies graph.",

    # ── Controls ──
    "Controls/SqlHighlightedEditor.cs": "Shared T-SQL editor control: highlighting, lint squiggles, diff line shading, find/fold/bookmark/goto wiring.",
    "Controls/EditorFindBar.cs": "Find & replace strip (Ctrl+F / Ctrl+H) built in code, with match highlighting and replace-all undo.",
    "Controls/EditorFolding.cs": "T-SQL folding: single-pass scanner for BEGIN/END, transactions, batches, comments, parens, plus FoldingManager glue.",
    "Controls/EditorBookmarks.cs": "SSMS-style bookmarks: Ctrl+B toggle, Ctrl+K / Ctrl+Shift+K navigate, glyph margin, marks remap on edits.",
    "Controls/EditorGotoLine.cs": "Ctrl+G go-to-line overlay: clamps past the end, rejects non-numbers, Escape to close.",
    "Controls/SqlCompletionProvider.cs": "IntelliSense-style completion data for the editor: keywords, schema objects and column names.",
    "Controls/PlanDiagramControl.cs": "Execution-plan diagram: left-to-right operator boxes with per-operator icons, details panel and Ctrl+wheel zoom.",
    "Controls/MiniChart.cs": "Sparkline chart control used by the DB Health graphs (CPU, waits).",
    "Controls/SearchableComboBox.cs": "ComboBox with a search box above the list, used by every dropdown that can hold many items.",
    "Controls/DiagramTableCard.axaml": "Layout of one draggable table card in the diagram canvas.",
    "Controls/DiagramTableCard.axaml.cs": "Diagram table card: columns, PK/FK markers, selection and drag behaviour.",

    # ── ViewModels ──
    "ViewModels/MainViewModel.cs": "Launcher view-model: the connection forms, the difference list, and both directions of the deployment script — UP preview and DOWN rollback, one of them shown at a time.",
    "ViewModels/QueryViewModel.cs": "Query window view-model: tabs, execute/cancel, results, plans, open/save, history, session restore and persist.",
    "ViewModels/DbManagerViewModel.cs": "Object Explorer view-model: server and database tree loading, filters, scripting, database switching, restore/backup, Agent job and new-object designer flows, all fail-closed when a dialog host is missing. ReloadFolderAsync re-queries a folder — including the eagerly-filled object folders, which have no Loader — so the tree shows what a create or drop just did to the server.",
    "ViewModels/DbHealthViewModel.cs": "DB Health view-model: polling, samples, blocking chain, KILL, error log tail and the Query Store tab (state banner, regressed and top queries, plan list, force/unforce behind the confirmation host).",
    "ViewModels/DiagramViewModel.cs": "Diagram view-model: schema load, table search, layout, persistence.",
    "ViewModels/DataCompareViewModel.cs": "Data compare view-model: two connections, table discovery, the row-level comparison run, and the save/copy of the script it never executes.",
    "ViewModels/QueryBuilderViewModel.cs": "Query Constructor view-model: joins, filters, grouping, ordering, regeneration of the SQL on every change.",

    # ── Models ──
    "Models/ConnectionInfo.cs": "Connection parameters (server, DB, Windows/SQL/Entra auth, TLS), the connection strings they build, a log-safe label and the sibling-database clone the explorer switches to.",
    "Models/SavedConnection.cs": "A saved connection profile: its authentication method, how its password is held and how it becomes a ConnectionInfo.",
    "Models/ServerBrowserModels.cs": "Rows behind the server-scope tree nodes: instance overview, databases with state and size, logins and server roles, linked servers, Agent jobs.",
    "Models/AuthMethod.cs": "The authentication dropdown: Windows, SQL and the Entra ID flows, each mapped to the SqlClient Authentication= value it emits.",
    "Models/AppSettings.cs": "Persisted display preferences: UI zoom and editor font size.",
    "Models/QueryTab.cs": "One open query tab: text, file path, dirty flag, results, execution state.",
    "Models/QueryResultTable.cs": "One result set or affected-rows summary produced by a batch.",
    "Models/QueryHistoryEntry.cs": "One persisted history entry: script, timing, server, database, outcome.",
    "Models/SchemaDiffItem.cs": "One schema-compare diff line and its Added/Removed/Modified status.",
    "Models/CompareResultSummary.cs": "Aggregate counts for a schema-compare run.",
    "Models/ManagerTreeModels.cs": "Object Explorer node model: NodeKind for both the database and the server scope, ManagerNode with its lazy loader and context-menu flags, ExplorerQueryFilter and the index/key metadata records.",
    "Models/DataCompareModels.cs": "Data compare records: the per-table entry with its discovered key and shared columns, one differing row, and a table's diff with its insert/update/delete statements.",
    "Models/ObjectDependencyModels.cs": "Object dependency graph: one Uses/Used-by edge with its sys type_desc translated for a DBA, and the whole set of neighbours around one catalog object.",
    "Models/DbObjectInfo.cs": "Object list row for the tree (schema, name, DbObjectType).",
    "Models/TableColumn.cs": "Column metadata with human-readable type, nullability and defaults.",
    "Models/TableFilter.cs": "One WHERE-clause filter row used by the grid data tab.",
    "Models/TablePropertiesModels.cs": "Read-only per-table properties snapshot: space, columns, PK, FKs both ways, checks, indexes, triggers, stats, partitions.",
    "Models/RestoreModels.cs": "Restore domain model: BackupSetInfo, BackupFileInfo, RestorePlan and its validation rules.",
    "Models/BackupModels.cs": "Backup request model for the native BACKUP statement.",
    "Models/DbHealthModels.cs": "Health rows from DMVs: CPU samples, processes, waits, counters, missing indexes, deadlocks, plus QueryStoreState (option banner text) and the regressed/top/plan rows.",
    "Models/HealthActionsModels.cs": "Rows for the health actions: error log record and one blocking-chain link.",
    "Models/ExecutionPlanModel.cs": "Parsed execution plan: operators, statements, missing-index suggestions.",
    "Models/DiagramModels.cs": "Diagram state: table nodes, columns, relations and the persisted layout.",
    "Models/QueryBuilderModel.cs": "Query Constructor state: aggregate functions, filter operators, join options.",
    "Models/DataMoveTable.cs": "Data-move model: eligible tables, plan, relation order and per-table result.",
    "Models/StoredProcParam.cs": "One stored-procedure parameter and the value typed on the Execute tab.",

    # ── Services ──
    "Services/DbManagerService.cs": "Data access for Object Explorer: object and server-level browsing (databases, logins, linked servers, Agent jobs), object scripting, restore media reads, table/database properties.",
    "Services/ManagerScriptBuilder.cs": "Pure T-SQL builders: script-as, index/partition DDL, CreateObject for the designer, restore batches, backup/verify, SQL Agent job calls and the Query Store force/unforce/enable scripts — preview equals execution, and an invalid definition or id throws a one-line reason instead of emitting broken DDL.",
    "Services/DataCompareService.cs": "Row-level key comparison: table discovery with shared keys, the streamed row diff with its literal key pairing, value equality by type, and the review-first insert/update/delete script it writes without ever executing SQL against the target.",
    "Services/DatabaseBackupService.cs": "Native BACKUP DATABASE/LOG plus VERIFYONLY, and the older DacFx BACPAC export.",
    "Services/DbHealthService.cs": "DMV reads for health, blocking chain walk, KILL, the xp_readerrorlog tail, and the Query Store reads (version-tolerant options, regressed halves, ranked top queries, plans per query).",
    "Services/QueryExecutionService.cs": "Executes ad-hoc batches: GO splitting, cancellation, messages, result streaming, statistics and plan capture.",
    "Services/ExecutionPlanService.cs": "Parses ShowPlanXML into the plan model, for both estimated and actual plans.",
    "Services/SchemaCompareService.cs": "DacFx schema compare and the one comparison path behind both script directions — forward deploy, reversed rollback — with the function-before-view reorder and the deploy-database retargeting.",
    "Services/DataMoveService.cs": "Row synchronization between two databases in safe dependency order.",
    "Services/QuerySchemaService.cs": "Schema cache used by IntelliSense: tables, views, columns, loaded lazily per connection.",
    "Services/QueryBuilderService.cs": "Extras for the Constructor: FK-based join suggestions and per-table column lists.",
    "Services/SqlBuilder.cs": "Pure T-SQL generator for the visual Query Constructor.",
    "Services/SqlExplainerService.cs": "Deterministic plain-English analysis of a script: steps, joins, effects and safety warnings.",
    "Services/SqlKeywordLibrary.cs": "Hand-written teaching content for the keyword explainer dialog.",
    "Services/SqlLintService.cs": "Editor diagnostics: unmatched delimiters, typos, unknown tables, unqualified columns.",
    "Services/TsqlHighlighting.cs": "Loads the bundled TSQL.xshd into the editor's highlighting definitions.",
    "Services/LineDiffer.cs": "Line-level LCS diff used to colour source-only and target-only lines.",
    "Services/ResultsExportService.cs": "Renders results as TSV, CSV, JSON, Markdown or INSERT scripts, and works out the INSERT target from the script.",
    "Services/SqlFormatter.cs": "T-SQL beautifier behind Ctrl+Shift+F: tokenizes first, so only case, whitespace and line breaks change.",
    "Services/QueryHistoryService.cs": "Persistent, capped query history store in the data folder.",
    "Services/TabSessionService.cs": "Saves and restores the open query tabs across runs.",
    "Services/RecentFilesService.cs": "Most-recently-opened .sql paths, stored without file contents.",
    "Services/SavedConnectionsService.cs": "Reads and writes saved connection profiles, including DPAPI-protected passwords.",
    "Services/DiagramSchemaService.cs": "Reads tables, columns and foreign keys of one database for the diagram.",
    "Services/DiagramAutoLayoutService.cs": "Layered auto-layout: parents above children.",
    "Services/DiagramPersistenceService.cs": "Saves and loads diagram layouts as JSON.",
    "Services/AppLog.cs": "Rotating plain-text log; AppLog.RedirectDirectory is how the harness keeps probes out of the real log.",
    "Services/AppInfo.cs": "Version and environment facts shown in About and in diagnostics text.",
    "Services/AppSettingsService.cs": "Loads/saves settings.json and applies UI scale and fonts to Application.Resources.",
    "Services/ClipboardSafety.cs": "Never-throwing clipboard calls; the Avalonia cut/copy/paste crash workaround.",
    "Services/ClipboardGuard.cs": "Routes an editor's Ctrl+C/X/V through ClipboardSafety so a locked clipboard cannot kill the app.",

    # ── Tier 2 round 4: import wizard ──
    "Models/ImportModels.cs": "ImportColumn (one file column and where it maps), TargetColumn, CsvTable and ImportResult for the import wizard.",
    "Services/CsvImportService.cs": "Reads a delimited file (RFC 4180 quoting), infers SQL types from a sample, builds the CREATE TABLE and bulk-loads rows in one transaction.",
    "ViewModels/ImportWizardViewModel.cs": "View-model of the import wizard: read file, review the mapping, match an existing table, then load — failing closed without a confirmation host.",
    "Views/ImportWizardWindow.axaml": "Import wizard layout: file and destination cards, editable column mapping grid, script preview pane.",
    "Views/ImportWizardWindow.axaml.cs": "Supplies the file picker and the script-confirmation dialog to the import view-model once its DataContext arrives.",

    # ── Tier 2 round 4: object designer ──
    "Models/ObjectDesignerModels.cs": "DesignerKind (table, view, procedure), one DesignerColumn per table column and the DesignerSpec the designer hands back with its Execute-now choice.",
    "Views/ObjectDesignerDialog.axaml": "New Table / View / Stored Procedure dialog: kind, schema and name, a column grid for tables or a T-SQL body editor for views and procedures, over a live script preview.",
    "Views/ObjectDesignerDialog.axaml.cs": "Drives the object designer: swaps the column grid for the body editor by kind, keeps the preview equal to the statement that would run, and refuses to close on a definition the builder rejects.",

    # ── Styles / Resources / scripts ──
    "Styles/Resources.axaml": "Shared brushes, spacing and typography resources referenced across all windows.",
    "Styles/Styles.axaml": "App-wide control styles (buttons, tree, tabs, grids, dialogs).",
    "Resources/TSQL.xshd": "T-SQL syntax highlighting definition embedded into the assembly.",
    "Scripts/EgyptMart_HealthMonitor_Load.sql": "Sample load script that creates activity in EgyptMart so the health views have something to show.",
    "Tools/DBPressureTest.ps1": "PowerShell load generator used to exercise blocking, waits and CPU sampling.",
}
